Жогова Мария
itmo2022-verstka/task-1 pull request #16
Opened 2023-01-01 13:44 UTC by masha237

2023-01-02 10:00 UTC, trixartem requested changes
Замечания по реализации:
- Нарушены слои. Когда открываешь карточку на весь экран, то текст из подвала и полоска выше карточки
![image](https://user-images.githubusercontent.com/2376007/210216642-5b5cdcc9-4c86-4e82-b1fd-16551e95e737.png)

- Когда нажимаешь на "точку", то не показывается, какая выбрана
![image](https://user-images.githubusercontent.com/2376007/210216583-dd2cf555-d0f7-4057-a332-c3cf1967d469.png)

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.css
> +  order: 2;
Для чего это свойство?

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.css
> +* {
Для чего нужен этот блок?

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.css
> +#slide1:checked ~ .slides #slide_1 a img,
Можно избежать такого каскада - указать вместо img какой-нибудь класс

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.css
> +  -webkit-transform: translate(0, -500%);
Это точно еще актуально?

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.css
> +  z-index: 11;
Постарайся избегать большого количества z-index

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.css
> +  color: white;
Лучше использовать hex-запись

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.css
> +  -o-transition: -o-transform .5s ease-out;
не актуальные префиксы

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.css
> +  z-index: 12;
Можно без z-index обойтись

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.css
> +#close {
Почему обращение по id?

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.html
> +        <div class="overlay">Ушастик</div>
Можно использовать тег заголовка h1..h6

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.html
> +  <nav class="contacts">
Разве это навигация?

2023-01-02 10:00 UTC, trixartem commented on about-cats/src/index.html
> +<div class="header">
Тут тоже стоит использовать семантический тег

2023-01-15 21:19 UTC, masha237 commented on about-cats/src/index.html
> +<div class="header">
fixed

2023-01-15 21:19 UTC, masha237 commented on about-cats/src/index.html
> +  <nav class="contacts">
fixed

2023-01-15 21:19 UTC, masha237 commented on about-cats/src/index.html
> +        <div class="overlay">Ушастик</div>
fixed

2023-01-15 21:20 UTC, masha237 commented on about-cats/src/index.css
> +  -webkit-transform: translate(0, -500%);
fixed

2023-01-15 21:20 UTC, masha237 commented on about-cats/src/index.css
> +#slide1:checked ~ .slides #slide_1 a img,
fixed

2023-01-15 21:20 UTC, masha237 commented on about-cats/src/index.css
> +* {
fixed

2023-01-15 21:20 UTC, masha237 commented on about-cats/src/index.css
> +  order: 2;
fixed

2023-01-15 21:21 UTC, masha237 commented on about-cats/src/index.css
> +  color: white;
fixed

2023-01-15 21:21 UTC, masha237 commented on about-cats/src/index.css
> +  -o-transition: -o-transform .5s ease-out;
fixed

2023-01-15 22:22 UTC, masha237 commented on about-cats/src/index.css
> +  z-index: 11;
fixed

2023-01-15 22:22 UTC, masha237 commented on about-cats/src/index.css
> +  z-index: 12;
fixed

2023-01-15 22:22 UTC, masha237 commented on about-cats/src/index.css
> +#close {
fixed

2023-01-17 18:50 UTC, trixartem commented
✅  Принято

2023-01-27 20:17 UTC, closed without merging