Семисчастнов Данила
itmo2022-verstka/task-1 pull request #17
Opened 2023-01-05 22:08 UTC by semischastnoff

2023-01-17 18:54 UTC, trixartem commented
При наведении что-то идет не так
![image](https://user-images.githubusercontent.com/2376007/212986695-a9650c90-ab17-4e57-8b4a-0d279f6a4e0c.png)

2023-01-17 19:01 UTC, trixartem requested changes

2023-01-17 19:01 UTC, trixartem commented on about-cats/src/index.html
> +    <div class="header"><span class="firstHeaderLetter">М</span>урмаркет</div>
Не хватает семантики

2023-01-17 19:01 UTC, trixartem commented on about-cats/src/index.html
> +            <a href="#secondFullInfo">Бородач</a>
Похоже на заголовок

2023-01-17 19:01 UTC, trixartem commented on about-cats/src/index.css
> +    margin: 300px 0;
❌  cодержимое центрируется по вертикали и горизонтали.

2023-01-17 19:01 UTC, trixartem commented on about-cats/src/index.css
> +	background: #FFFFFF;
можно просто #fff

2023-01-17 19:01 UTC, trixartem commented on about-cats/src/index.css
> +.ul {
А зачем такие классы писать? Можно же как-то семантичнее назвать, например list или cat-list

2023-01-18 09:36 UTC, semischastnoff commented
<img width="1680" alt="Снимок экрана 2023-01-18 в 13 33 59" src="https://user-images.githubusercontent.com/72871438/213135901-11723968-3269-41bd-b121-bdd1e958a381.png">
странно, у меня все в порядке, проверил в хроме и в сафари

2023-01-23 08:49 UTC, trixartem requested changes

2023-01-23 08:49 UTC, trixartem commented on about-cats/src/index.css
> +    left: 50px;
Тут очень странное смещение, скорее всего из-за него все едет

2023-01-26 18:52 UTC, trixartem commented
✅  Принято

2023-01-26 18:52 UTC, closed without merging