Task-1
itmo2022-verstka/task-1 pull request #18
Opened 2023-01-09 13:11 UTC by tattosha01

Murmarket: scroll-table and tape-carousel

2023-03-15 19:42 UTC, trixartem requested changes

2023-03-15 19:42 UTC, trixartem commented on about-cats/src/index.html
> +      <span class="ya-letter">М</span>урмаркет
не хватает семантики

2023-03-15 19:42 UTC, trixartem commented on about-cats/src/index.css
> +  padding-top: 30%;
А почему вертикальный отступ в процентах?

2023-03-15 19:42 UTC, trixartem commented on about-cats/src/index.css
> +  background-color: #ffffff;
можно короче #fff

2023-03-19 17:05 UTC, tattosha01 commented on about-cats/src/index.css
> +  background-color: #ffffff;
Как и ddd, поправил

2023-03-19 18:30 UTC, tattosha01 commented on about-cats/src/index.css
> +  padding-top: 30%;
Прочитал как следует выравнивать текст, поправил

2023-03-19 18:31 UTC, tattosha01 commented on about-cats/src/index.html
> +      <span class="ya-letter">М</span>урмаркет
Поправил (если ишью про header-style)

2023-03-22 20:20 UTC, trixartem commented
✅ Принято

2023-03-22 20:20 UTC, closed without merging